-- Seed 20 Core Templates
insert into public.templates (id, slug, name, image_url, boxes, is_active, display_order)
values
(1, 'confused-nick', 'Confused Nick Young', '/templates/cdn/1.webp', '[{"id":"top","label":"Top Text","placeholder":"Top Text","x":0.5,"y":0.12,"textAlign":"center"},{"id":"bottom","label":"Bottom Text","placeholder":"Bottom Text","x":0.5,"y":0.88,"textAlign":"center"}]'::jsonb, true, 1),
(2, 'left-exit-12', 'Left Exit 12 - Car Swerving', '/templates/cdn/2.webp', '[{"id":"straight","label":"Straight Road (Left Sign)","placeholder":"Keep doing this...","x":0.35,"y":0.28,"textAlign":"center","maxWidthRatio":0.32},{"id":"exit","label":"Exit Ramp (Right Sign)","placeholder":"Exciting new thing...","x":0.72,"y":0.28,"textAlign":"center","maxWidthRatio":0.34},{"id":"car","label":"Car (Bottom Right)","placeholder":"Me / Everyone","x":0.72,"y":0.85,"textAlign":"center","maxWidthRatio":0.35}]'::jsonb, true, 2),
(3, 'two-buttons', 'Two Buttons', '/templates/cdn/3.webp', '[{"id":"btn1","label":"Left Button","placeholder":"Option 1","x":0.3,"y":0.16,"textAlign":"center","maxWidthRatio":0.28,"fontSizeRatio":0.8},{"id":"btn2","label":"Right Button","placeholder":"Option 2","x":0.63,"y":0.14,"textAlign":"center","maxWidthRatio":0.28,"fontSizeRatio":0.8},{"id":"guy","label":"Guy Sweating","placeholder":"Me trying to decide...","x":0.5,"y":0.88,"textAlign":"center","maxWidthRatio":0.8}]'::jsonb, true, 3),
(4, 'epic-handshake', 'Epic Handshake', '/templates/cdn/4.webp', '[{"id":"left","label":"Left Arm (Dutch)","placeholder":"Group A...","x":0.25,"y":0.42,"textAlign":"center","maxWidthRatio":0.35},{"id":"right","label":"Right Arm (Dillon)","placeholder":"Group B...","x":0.75,"y":0.4,"textAlign":"center","maxWidthRatio":0.35},{"id":"center","label":"Handshake / Agreement","placeholder":"Mutual agreement","x":0.5,"y":0.75,"textAlign":"center","maxWidthRatio":0.5}]'::jsonb, true, 4),
(5, 'change-my-mind', 'Change My Mind', '/templates/cdn/5.webp', '[{"id":"board","label":"Sign on Table","placeholder":"Your controversial statement...","x":0.5,"y":0.68,"textAlign":"center","maxWidthRatio":0.48,"fontSizeRatio":0.85},{"id":"top","label":"Top Header (Optional)","placeholder":"Top Text...","x":0.5,"y":0.12,"textAlign":"center","maxWidthRatio":0.85}]'::jsonb, true, 5),
(6, 'distracted-boyfriend', 'Distracted Boyfriend', '/templates/cdn/6.webp', '[{"id":"red","label":"Girl in Red (Left)","placeholder":"New distraction...","x":0.2,"y":0.65,"textAlign":"center","maxWidthRatio":0.3},{"id":"guy","label":"Distracted Guy (Middle)","placeholder":"Me...","x":0.52,"y":0.48,"textAlign":"center","maxWidthRatio":0.3},{"id":"gf","label":"Girlfriend (Right)","placeholder":"My current responsibilities...","x":0.82,"y":0.6,"textAlign":"center","maxWidthRatio":0.3}]'::jsonb, true, 6),
(7, 'woman-yelling-at-cat', 'Woman Yelling at Cat', '/templates/cdn/7.webp', '[{"id":"woman","label":"Woman Yelling (Left)","placeholder":"You promised...","x":0.25,"y":0.18,"textAlign":"center","maxWidthRatio":0.42},{"id":"cat","label":"Cat (Right)","placeholder":"Me at 3 AM...","x":0.75,"y":0.18,"textAlign":"center","maxWidthRatio":0.42}]'::jsonb, true, 7),
(8, 'buff-doge-vs-cheems', 'Buff Doge vs. Cheems', '/templates/cdn/8.webp', '[{"id":"doge","label":"Buff Doge (Left)","placeholder":"Me in 2012...","x":0.25,"y":0.8,"textAlign":"center","maxWidthRatio":0.42},{"id":"cheems","label":"Cheems (Right)","placeholder":"Me in 2024...","x":0.75,"y":0.84,"textAlign":"center","maxWidthRatio":0.42},{"id":"top","label":"Comparison Title","placeholder":"Before vs Now...","x":0.5,"y":0.1,"textAlign":"center","maxWidthRatio":0.85}]'::jsonb, true, 8),
(9, 'bernie-sanders', 'Bernie I Am Once Again Asking', '/templates/cdn/9.webp', '[{"id":"top","label":"Top Text","placeholder":"Top Text...","x":0.5,"y":0.12,"textAlign":"center"},{"id":"bottom","label":"Bottom Text","placeholder":"I am once again asking for...","x":0.5,"y":0.88,"textAlign":"center"}]'::jsonb, true, 9),
(10, 'always-has-been', 'Always Has Been', '/templates/cdn/10.webp', '[{"id":"earth","label":"Earth / Discovery (Left)","placeholder":"Wait, it''s all ...?","x":0.32,"y":0.4,"textAlign":"center","maxWidthRatio":0.38},{"id":"gun","label":"Astronaut with Gun (Right)","placeholder":"Always has been.","x":0.78,"y":0.25,"textAlign":"center","maxWidthRatio":0.38}]'::jsonb, true, 10),
(11, 'jim-halpert-whiteboard', 'Jim Halpert Explaining to Whiteboard', '/templates/cdn/11.webp', '[{"id":"board","label":"Whiteboard Text","placeholder":"Here is the truth...","x":0.68,"y":0.45,"textAlign":"center","maxWidthRatio":0.45},{"id":"jim","label":"Jim / Header","placeholder":"Explaining to everyone...","x":0.25,"y":0.25,"textAlign":"center","maxWidthRatio":0.35}]'::jsonb, true, 11),
(12, 'laughing-leo', 'Leonardo DiCaprio Laughing', '/templates/cdn/12.webp', '[{"id":"top","label":"Top Text","placeholder":"Top Text","x":0.5,"y":0.12,"textAlign":"center"},{"id":"bottom","label":"Bottom Text","placeholder":"Bottom Text","x":0.5,"y":0.88,"textAlign":"center"}]'::jsonb, true, 12),
(13, 'anakin-and-padme', 'Anakin and Padme', '/templates/cdn/13.webp', '[{"id":"p1","label":"Anakin (Top Left)","placeholder":"I''m going to change things...","x":0.25,"y":0.4,"textAlign":"center","maxWidthRatio":0.42},{"id":"p2","label":"Padme (Top Right)","placeholder":"For the better, right?","x":0.75,"y":0.4,"textAlign":"center","maxWidthRatio":0.42},{"id":"p3","label":"Padme Worried (Bottom Right)","placeholder":"...For the better, right?","x":0.75,"y":0.9,"textAlign":"center","maxWidthRatio":0.42}]'::jsonb, true, 13),
(14, 'trade-offer', 'Trade Offer', '/templates/cdn/14.webp', '[{"id":"receive","label":"i receive (Left)","placeholder":"Your code with 0 bugs...","x":0.25,"y":0.35,"textAlign":"center","maxWidthRatio":0.42},{"id":"give","label":"you receive (Right)","placeholder":"A working production build...","x":0.75,"y":0.35,"textAlign":"center","maxWidthRatio":0.42}]'::jsonb, true, 14),
(15, 'panik-kalm-panik', 'Panik Kalm Panik', '/templates/cdn/15.webp', '[{"id":"panik1","label":"Top Panik","placeholder":"Server went down!","x":0.7,"y":0.18,"textAlign":"center","maxWidthRatio":0.45},{"id":"kalm","label":"Middle Kalm","placeholder":"It''s just a test server.","x":0.7,"y":0.52,"textAlign":"center","maxWidthRatio":0.45},{"id":"panik2","label":"Bottom Panik","placeholder":"Wait, test is connected to prod database!","x":0.7,"y":0.85,"textAlign":"center","maxWidthRatio":0.45}]'::jsonb, true, 15),
(16, 'expanding-brain', 'Expanding Brain', '/templates/cdn/16.webp', '[{"id":"b1","label":"Small Brain (Level 1)","placeholder":"Level 1 thought...","x":0.25,"y":0.14,"textAlign":"center","maxWidthRatio":0.45},{"id":"b2","label":"Glowing Brain (Level 2)","placeholder":"Level 2 thought...","x":0.25,"y":0.39,"textAlign":"center","maxWidthRatio":0.45},{"id":"b3","label":"Cosmic Brain (Level 3)","placeholder":"Level 3 thought...","x":0.25,"y":0.64,"textAlign":"center","maxWidthRatio":0.45},{"id":"b4","label":"Universe Brain (Level 4)","placeholder":"Galaxy brain thought...","x":0.25,"y":0.89,"textAlign":"center","maxWidthRatio":0.45}]'::jsonb, true, 16),
(17, 'is-this-a-pigeon', 'Is This a Pigeon?', '/templates/cdn/17.webp', '[{"id":"man","label":"Man (Left)","placeholder":"Me...","x":0.32,"y":0.45,"textAlign":"center","maxWidthRatio":0.35},{"id":"butterfly","label":"Butterfly (Right)","placeholder":"A slight bug...","x":0.68,"y":0.3,"textAlign":"center","maxWidthRatio":0.35},{"id":"bottom","label":"Subtitle","placeholder":"Is this a critical outage?","x":0.5,"y":0.88,"textAlign":"center","maxWidthRatio":0.85}]'::jsonb, true, 17),
(18, 'disaster-girl', 'Disaster Girl', '/templates/cdn/18.webp', '[{"id":"fire","label":"House on Fire","placeholder":"Production on Friday 5PM...","x":0.55,"y":0.15,"textAlign":"center","maxWidthRatio":0.75},{"id":"girl","label":"Smiling Girl","placeholder":"Me turning off notifications...","x":0.35,"y":0.85,"textAlign":"center","maxWidthRatio":0.6}]'::jsonb, true, 18),
(19, 'theyre-the-same-picture', 'They''re the Same Picture', '/templates/cdn/19.webp', '[{"id":"pam","label":"Pam / Corporate","placeholder":"Corporate needs you to find differences...","x":0.5,"y":0.15,"textAlign":"center","maxWidthRatio":0.8},{"id":"pic1","label":"Picture 1 (Left)","placeholder":"Javascript","x":0.28,"y":0.78,"textAlign":"center","maxWidthRatio":0.4},{"id":"pic2","label":"Picture 2 (Right)","placeholder":"Typescript without types","x":0.72,"y":0.78,"textAlign":"center","maxWidthRatio":0.4}]'::jsonb, true, 19),
(20, 'hide-the-pain-harold', 'Hide the Pain Harold', '/templates/cdn/20.webp', '[{"id":"top","label":"Top Text","placeholder":"When everything is on fire...","x":0.5,"y":0.12,"textAlign":"center"},{"id":"bottom","label":"Bottom Text","placeholder":"...but you have to smile in the meeting","x":0.5,"y":0.88,"textAlign":"center"}]'::jsonb, true, 20)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  image_url = excluded.image_url,
  boxes = excluded.boxes,
  is_active = excluded.is_active,
  display_order = excluded.display_order,
  updated_at = now();
